import LuigiClient from './luigi-client';

export default LuigiClient;
export const uxManager = LuigiClient.uxManager;
export const linkManager = LuigiClient.linkManager;
export const lifecycleManager = LuigiClient.lifecycleManager;
export const storageManager = LuigiClient.storageManager;

export const addInitListener = LuigiClient.addInitListener;
export const removeInitListener = LuigiClient.removeInitListener;
export const addContextUpdateListener = LuigiClient.addContextUpdateListener;
export const removeContextUpdateListener = LuigiClient.removeContextUpdateListener;
export const getToken = LuigiClient.getToken;
export const getEventData = LuigiClient.getEventData;
export const getContext = LuigiClient.getContext;
export const addNodeParams = LuigiClient.addNodeParams;
export const getNodeParams = LuigiClient.getNodeParams;
export const getActiveFeatureToggles = LuigiClient.getActiveFeatureToggles;
export const getPathParams = LuigiClient.getPathParams;
export const getCoreSearchParams = LuigiClient.getCoreSearchParams;
export const addCoreSearchParams = LuigiClient.addCoreSearchParams;
export const getClientPermissions = LuigiClient.getClientPermissions;
export const sendCustomMessage = LuigiClient.sendCustomMessage;
export const addCustomMessageListener = LuigiClient.addCustomMessageListener;
export const removeCustomMessageListener = LuigiClient.removeCustomMessageListener;
export const addInactiveListener = LuigiClient.addInactiveListener;
export const removeInactiveListener = LuigiClient.removeInactiveListener;
export const setTargetOrigin = LuigiClient.setTargetOrigin;
export const getUserSettings = LuigiClient.getUserSettings;
export const isLuigiClientInitialized = LuigiClient.isLuigiClientInitialized;
export const luigiClientInit = LuigiClient.luigiClientInit;
export const getAnchor = LuigiClient.getAnchor;
export const setAnchor = LuigiClient.setAnchor;
export const setViewGroupData = LuigiClient.setViewGroupData;
